export const settingsIcons = {
  pro: '⚡',
  snooze: '⏰',
  sound: '🎵',
  vibration: '📳',
  volume: '🔊',
  theme: '🌙',
  notifications: '🔔',
  upcoming: '📅',
  website: '🌐',
  rating: '⭐',
  info: 'ℹ️',
  cancelSubscription: '🚫',
  signOut: '🚪',
  closeAccount: '⚠️',
  chevron: '›',
  alarms: '🏠',
  history: '📅',
  templates: '📦',
  settings: '⚙️',
} as const;
